### ISSUE TITLE
Fix segfault in cunicu status

### ISSUE THREAD

**Issue by stv0g** [stv0g/cunicu#171]
```
interface: wg0
  public key: LzJOjsZYehT96Hr6lVnWEpq1BUNTpN47KZe7tfQEEy8=
  listening port: 51820
  type: KERNEL_OPENBSD
  ifindex: 4
  mtu: 1420
  latest sync: Now

  nat type: NFTABLES
  mux ports: 60197, 39934

  peer:
    public key: UlNG3iHcOW6n3TNPMdJhncFiiARhoxhKf/pHCBibnC4=
  state: NEW
    allowed ips: 10.237.185.237/32, fc2f:9a4d:b9ed:7c12:4ff7:3dbf:d8bc:736d/128
    protocol version: 1

    proxy type: NO_PROXY
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x588d60]

goroutine 1 [running]:
github.com/stv0g/cunicu/pkg/proto.(*Timestamp).Time(...)
	/home/stv0g/workspace/cunicu/pkg/proto/common.go:24
github.com/stv0g/cunicu/pkg/proto/feature/epdisc.(*Peer).Dump(0x400039ed80, {0xae3ba0?, 0x40003b6870}, 0x5)
	/home/stv0g/workspace/cunicu/pkg/proto/feature/epdisc/epdisc.go:90 +0x150
github.com/stv0g/cunicu/pkg/proto/core.(*Peer).Dump(0x40003961c0, {0xae3ba0?, 0x40003b6600}, 0x5)
	/home/stv0g/workspace/cunicu/pkg/proto/core/peer.go:139 +0xd04
github.com/stv0g/cunicu/pkg/proto/core.(*Interface).Dump(0x4000269130, {0xae52e0?, 0x400019a008}, 0x5)
	/home/stv0g/workspace/cunicu/pkg/proto/core/interface.go:93 +0x878
github.com/stv0g/cunicu/pkg/proto/rpc.(*GetStatusResp).Dump(0x4000287340?, {0xae52e0, 0x400019a008}, 0x0?)
	/home/stv0g/workspace/cunicu/pkg/proto/rpc/rpc.go:19 +0xa8
main.status(0x0?, {0x4000286cb0, 0x0, 0x0?}, 0x4000196e58)
	/home/stv0g/workspace/cunicu/cmd/cunicu/status.go:93 +0x6b8
main.init.11.func1(0x40002c6f00?, {0x4000286cb0?, 0x0?, 0x1?})
	/home/stv0g/workspace/cunicu/cmd/cunicu/status.go:33 +0x24
github.com/spf13/cobra.(*Command).execute(0x40002c6f00, {0x4000286c90, 0x1, 0x1})
	/home/stv0g/.gvm/pkgsets/go1.20.1/global/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x5ac
github.com/spf13/cobra.(*Command).ExecuteC(0x10c34c0)
	/home/stv0g/.gvm/pkgsets/go1.20.1/global/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
	/home/stv0g/.gvm/pkgsets/go1.20.1/global/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/home/stv0g/workspace/cunicu/cmd/cunicu/root.go:150 +0x78
```

**Comment by stv0g** [comment]
Fixed by b9fbc86513e1f12ea5fd47bffe84b8e6517617b7
